Add controllers
Evgeny2835/ShareIt pull request #1
Opened 2022-07-28 15:51 UTC by Evgeny2835

2022-07-29 07:40 UTC, kukolev requested changes

2022-07-29 07:40 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userService.isUserIdExists(userId)) {
Валидации лучше вынести в отдельный приватный метод. Так код будет понятней.

2022-07-29 07:40 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +public class ItemServiceImpl implements ItemService {
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-07-29 15:10 UTC, Evgeny2835 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userService.isUserIdExists(userId)) {
Исправил.
Изначально делал приватный метод, но мне не нравилось, что после валидации одному вызывающему методу требуется Item для дальнейшей работы, а второму - нет.
Раньше у меня все методы валидации возвращали boolean, а здесь требовался объект, засомневался, как правильно и ..........все снес.
Дублирование 10 строчек кода, это, конечно, не очень хорошо, даже среда разработки "сигнализировала", но все-таки не стал делать в первом варианте приватный метод.

2022-07-29 15:52 UTC, Evgeny2835 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +public class ItemServiceImpl implements ItemService {
Исправил на свое усмотрение, но ..........
Информация на курсе по логам общего характера, ее недостаточно.
Когда пишешь проект, всегда возникают вопросы, где и что логировать, как писать сообщения об этом
Лаконичность кода не всегда позволяет корректно вставить лог.

Пример того, что написал.
  @Override
    public ItemDto add(Long userId, ItemDto itemDto) {
        if (userService.isUserIdExists(userId)) {
            throw new NotFoundException(String.format("User not found: id=%d", userId));
        }
        Item item = ItemMapper.toItem(itemDto, userId);
        **log.info("Convert itemDto to item {}", item);**
        return ItemMapper.toItemDto(itemRepository.add(item));

1. Залогировал создание item.
2. itemRepository.add(item) - за логирование добавление item отвечает метод репозитория.
3. Как быть с конвертацией item в itemDto после успешного добавления item в хранилище?
    Нужно логировать или нет?
    Если нужно, то как?
    Все же написано одной лаконичной строкой, включая возвращаемое значение:
              return ItemMapper.toItemDto(itemRepository.add(item));
    Можно, конечно, ввести локальные переменные, разбив на этапы, после которых писать лог, но тогда не будет 
    лаконичности.
    
Понимаю, что все не залогируешь, но избыточность тоже плохо.
В общем, как понял на своем "бытовом" уровне, так дополнил код.

2022-07-30 08:51 UTC, kukolev requested changes

2022-07-30 08:51 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +public class ItemServiceImpl implements ItemService {
Сергей, логи у вас нормально получились. Канонического подхода обычно нет и на практике обычно логируют сложную логику. Цель логов - дать понимание что вообще происходит, когда что-то пойдет не так.

2022-07-30 08:51 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private Item checkUserAndItemExistAndUserIsOwnerOfItem(Long userId, Long itemId) {
По моему название получилось громоздким и лучше бы его сделать поменьше. 

Также название не отражает назначение метода - метод возвращает данные, что не видно из названия.

Предлагаю переименовать метод.

2022-07-30 21:42 UTC, Evgeny2835 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private Item checkUserAndItemExistAndUserIsOwnerOfItem(Long userId, Long itemId) {
Ок.
Метод переименован.

2022-07-31 16:28 UTC, kukolev approved these changes

2022-08-12 14:13 UTC, merged