TZ-14 review 1
Evgeny2835/ShareIt pull request #2
Opened 2022-08-20 10:27 UTC by Evgeny2835

2022-08-21 19:51 UTC, kukolev requested changes

2022-08-21 19:51 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    //Collection<Booking> getAllByItem(Long itemId);
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-21 19:51 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/dto/ItemRequestDto.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-21 19:51 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-22 06:44 UTC, Evgeny2835 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    //Collection<Booking> getAllByItem(Long itemId);
Исправлено.
Перед сдачей проекта специально проходился по всем классам, чтобы убрать "мусор", но .......

2022-08-22 06:50 UTC, Evgeny2835 commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Исправлено.

2022-08-22 07:09 UTC, Evgeny2835 commented on src/main/java/ru/practicum/shareit/requests/dto/ItemRequestDto.java
>  /**
Не стал ничего исправлять.
В части пакета "requests" - это еще заготовка от разработчиков курса, сам ничего не писал.
В ТЗ явно не указано про написание кода в этом пакете, вероятно, добавим в следующем спринте.
Кто-то из коллег писал, кто-то нет, я не стал по формальным причинам.

2022-08-22 20:47 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    //Collection<Booking> getAllByItem(Long itemId);
Бывает )

2022-08-22 20:52 UTC, kukolev approved these changes

2022-08-24 04:56 UTC, merged