Add item requests
Evgeny2835/ShareIt pull request #5
Opened 2022-09-10 17:05 UTC by Evgeny2835

2022-09-10 21:08 UTC, kukolev requested changes

2022-09-10 21:08 UTC, kukolev commented on pom.xml
> +			<version>42.4.2</version>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-10 21:08 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    UserDto newUserDtoOwner = UserDto.builder()
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    final LocalDateTime start = LocalDateTime.now().plusDays(1);
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ItemService itemService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemIntegrationTest.java
> +    UserDto newUserDto = UserDto.builder()
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    final User user = new User(USER_ID, USER_NAME, USER_EMAIL);
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +    ItemRequestService itemRequestService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestIntegrationTest.java
> +    final JdbcTemplate jdbcTemplate;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceTest.java
> +    UserService userService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserIntegrationTest.java
> +//@Rollback(false)
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserIntegrationTest.java
> +    final JdbcTemplate jdbcTemplate;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-10 21:08 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    static final Long USER_ID = 1L;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-11 07:47 UTC, Evgeny2835 commented on pom.xml
> +			<version>42.4.2</version>
Исправлено.
Никогда в pom.xml не задумывался о кодстайле.

2022-09-11 07:51 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    UserDto newUserDtoOwner = UserDto.builder()
Исправлено.

2022-09-11 07:54 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    final LocalDateTime start = LocalDateTime.now().plusDays(1);
Исправлено.

2022-09-11 07:57 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ItemService itemService;
Исправлено.

2022-09-11 07:59 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/item/ItemIntegrationTest.java
> +    UserDto newUserDto = UserDto.builder()
Исправлено.

2022-09-11 08:01 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    final User user = new User(USER_ID, USER_NAME, USER_EMAIL);
Исправлено.

2022-09-11 08:03 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +    ItemRequestService itemRequestService;
Исправлено.

2022-09-11 08:04 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/requests/ItemRequestIntegrationTest.java
> +    final JdbcTemplate jdbcTemplate;
Исправлено.

2022-09-11 08:07 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceTest.java
> +    UserService userService;
Исправлено.

2022-09-11 08:09 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    ObjectMapper mapper;
Исправлено.

2022-09-11 08:12 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/user/UserIntegrationTest.java
> +//@Rollback(false)
Исправлено.
Чистил, чистил код, но, как часто бывает, не дочистил.

2022-09-11 08:13 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/user/UserIntegrationTest.java
> +    final JdbcTemplate jdbcTemplate;
Исправлено.

2022-09-11 08:15 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    static final Long USER_ID = 1L;
Исправлено.

2022-09-11 10:51 UTC, Evgeny2835 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(
Исправлено.
С замечанием согласен на 100%, я причина такого когда банальна - слабые знания sql.
Тот единственный ранее имевшийся query-запрос был взят из примера в техническом задании к 14 спринту.
Только после замечаний стал его модернизировать.
Из-за отсутствия опыта в ИТ, есть постоянная боязнь что-то сломать и не восстановить.

2022-09-11 18:54 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(
Такая боязнь это нормально. С опытом приходит понимание, что можно починить любую проблему и никакой магии нет )

2022-09-11 19:07 UTC, kukolev requested changes

2022-09-11 19:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    BookingRepository bookingRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-11 19:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private final LocalDateTime start = LocalDateTime.now().plusDays(1);
Может так получиться, что в момент запуска тестов start и end будут отличаться не на один день, а на два. Это может произойти если start вычислялся в один день, а уже в следующий день. Лучше вычислять end на основе start:

`end = start.plusDays(1);`

2022-09-11 19:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +        LocalDateTime start = LocalDateTime.now().plusDays(1);
Может так получиться, что в момент запуска тестов start и end будут отличаться не на один день, а на два. Это может произойти если start вычислялся в один день, а уже в следующий день. Лучше вычислять end на основе start:

`end = start.plusDays(1);`

2022-09-11 19:07 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    final LocalDateTime start = LocalDateTime.now().plusDays(1);
Может так получиться, что в момент запуска тестов start и end будут отличаться не на один день, а на два. Это может произойти если start вычислялся в один день, а уже в следующий день. Лучше вычислять end на основе start:

`end = start.plusDays(1);`

2022-09-11 19:30 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    BookingRepository bookingRepository;
Исправил.
Невнимательность - наше все.

2022-09-11 19:33 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private final LocalDateTime start = LocalDateTime.now().plusDays(1);
Понял, исправил.

2022-09-11 19:35 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +        LocalDateTime start = LocalDateTime.now().plusDays(1);
Исправил.

2022-09-11 19:37 UTC, Evgeny2835 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    final LocalDateTime start = LocalDateTime.now().plusDays(1);
Исправил.

2022-09-12 09:14 UTC, kukolev approved these changes

2022-09-12 11:35 UTC, merged