Add docker
Evgeny2835/ShareIt pull request #7
Opened 2022-09-25 11:05 UTC by Evgeny2835

Добавил .github
При начале разработки в ветке add-docker удалил каталог, посчитал, что не нужен, не знаю, что меня "дернуло" удалить, раньше никогда так не делал.
При создании первого pull request еще удивлялся, почему не стартовали автотесты, думал, что так нужно.

2022-09-26 09:11 UTC, kukolev requested changes

2022-09-26 09:11 UTC, kukolev commented on checkstyle.xml
> +		<!--		<module name="CustomImportOrder">-->
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-26 09:11 UTC, kukolev commented on checkstyle.xml
> +		<!--			<property name="customImportOrderRules" value="STATIC###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE"/>-->
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-26 09:11 UTC, kukolev commented on checkstyle.xml
>  	<!--	<module name="NewlineAtEndOfFile"/>-->
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-26 09:11 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-26 09:11 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +	public static Optional<BookingState> from(String stringState) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-26 10:26 UTC, Evgeny2835 commented on checkstyle.xml
> +		<!--		<module name="CustomImportOrder">-->
Исправил.
В этот файл даже не заглядывал, он из заготовки Практикума.

2022-09-26 10:26 UTC, Evgeny2835 commented on checkstyle.xml
> +		<!--			<property name="customImportOrderRules" value="STATIC###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE"/>-->
Исправил.

2022-09-26 10:27 UTC, Evgeny2835 commented on checkstyle.xml
>  	<!--	<module name="NewlineAtEndOfFile"/>-->
Исправил.

2022-09-26 10:27 UTC, Evgeny2835 commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +	public static void main(String[] args) {
Исправил.

2022-09-26 10:28 UTC, Evgeny2835 commented on gateway/src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +	public static Optional<BookingState> from(String stringState) {
Исправил.

2022-09-27 07:01 UTC, kukolev requested changes

2022-09-27 07:01 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +    public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

Исправить нужно во всем файле.

2022-09-27 08:38 UTC, Evgeny2835 commented on gateway/src/main/java/ru/practicum/shareit/ShareItGateway.java
> +    public static void main(String[] args) {
Исправил.
Теперь понял, в чем проблема.
Когда корректировал в первый раз, не обратил внимание, что среда разработки визуально "соединяет" несколько строк маленьких методов в одну строку.
Фактически все строки остаются отдельными и каждая должна соответствовать код-стайлу.
Кстати, пока не понял, в чем смысл такой "помощи" со стороны среды разработки.

2022-09-28 09:54 UTC, kukolev approved these changes

2022-09-28 11:24 UTC, merged